version: "3.3"

services:
  # Web service layer
  nginx:
    image: nginx:alpine
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "9000:80"
    depends_on:
      - php
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure

  # Application service layer
  php:
    # Create an image (guanphp) on root folder php first! (docker build -t guanphp .)
    image: guanphp
    volumes:
      - "./app:/var/www/html"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
  
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=MyDBRoot123
      - MYSQL_DATABASE=cloud_computing
      - MYSQL_USER=php
      - MYSQL_PASSWORD=php
    deploy:
      mode: replicated
      replicas: 3
      labels: [MySQLDatabase]
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure

  phpmyadmin:
    ports:
      - "8080:80"
    image: phpmyadmin:latest
    environment: 
      - PMA_HOST=mysql
    deploy:
      mode: replicated
      replicas: 1
      labels: [Admin]
      restart_policy:
        condition: on-failure

  # Uncomment the following when on server to view the manager/worker
  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
